"""
Public package interface for the muon wire estimator.

This package provides a lightweight, self-contained estimator for the signal
visibility question:

    Given a muon passing near a wire, what direct image pulse and/or ordinary
    gas-avalanche pulse should I expect at the readout termination?

Level 1 exports deterministic mean-estimate helpers.
Later levels add stochastic event simulation and calibration infrastructure.
"""

from __future__ import annotations

from .core import (
    ESTIMATOR_VERSION,
    build_estimator_config,
    config_from_mapping,
    estimate,
    estimate_from_config,
    estimate_from_mapping,
    estimate_from_mapping_to_dict,
    estimate_to_dict,
    result_to_dict,
)
from .drift import (
    DriftEstimate,
    drift_summary,
    effective_drift_velocity_m_per_s,
    estimate_attachment_survival_fraction,
    estimate_collection_fraction_total,
    estimate_collected_primary_electrons,
    estimate_drift,
    estimate_drift_time_s,
)
from .gain import (
    GainEstimate,
    estimate_avalanche_charge_c,
    estimate_avalanche_electrons,
    estimate_gain,
    estimate_gas_gain,
    estimate_gas_gain_from_surface_field,
    gain_summary,
)
from .gases import (
    describe_gas,
    gas_to_dict,
    get_gas,
    has_gas,
    iter_builtin_gases,
    list_builtin_gases,
    merged_registry,
    register_gas,
    require_gas,
)
from .geometry import (
    VACUUM_PERMITTIVITY_F_PER_M,
    active_track_fraction,
    average_drift_field_v_per_m,
    clamp_radius_to_geometry,
    cylindrical_field_v_per_m,
    cylindrical_surface_field_v_per_m,
    direct_image_charge_sharing_factor,
    effective_wire_capacitance_f,
    geometry_from_mapping,
    geometry_summary,
    mean_drift_path_radius_m,
    potential_v,
    radial_drift_distance_m,
    track_radius_m,
    validate_geometry,
    wire_capacitance_per_length_f_per_m,
)
from .ionization import (
    CM_PER_M,
    ELECTRON_CHARGE_C as PRIMARY_ELECTRON_CHARGE_C,
    EV_PER_MEV,
    IonizationEstimate,
    estimate_direct_image_charge_c,
    estimate_mean_ionization,
    estimate_primary_statistics_proxy,
    ionization_summary,
    mean_cluster_count,
    mean_primary_charge_c,
    mean_primary_electrons_from_energy_loss,
    track_energy_loss_ev,
    track_energy_loss_mev,
)
from .models import (
    CalibrationRecord,
    DeterministicEstimate,
    EstimatorConfig,
    EventPulseRecord,
    EventSimulationConfig,
    EventSimulationSummary,
    GasModel,
    GeometryModel,
    JSONScalar,
    JSONValue,
    PulseEstimate,
    dataclass_to_dict,
    merge_mappings,
)
from .pulse import (
    PulseComputation,
    build_avalanche_pulse,
    build_direct_image_pulse,
    build_pulse_estimate,
    compute_pulse,
    effective_pulse_width_s,
    peak_current_a,
    peak_voltage_v,
    pulse_summary,
    pulse_width_s,
    rc_time_constant_s,
)

__version__ = ESTIMATOR_VERSION

__all__ = [
    "__version__",
    "ESTIMATOR_VERSION",
    "JSONScalar",
    "JSONValue",
    "GeometryModel",
    "GasModel",
    "EstimatorConfig",
    "PulseEstimate",
    "DeterministicEstimate",
    "EventPulseRecord",
    "EventSimulationConfig",
    "EventSimulationSummary",
    "CalibrationRecord",
    "dataclass_to_dict",
    "merge_mappings",
    "get_gas",
    "require_gas",
    "has_gas",
    "list_builtin_gases",
    "iter_builtin_gases",
    "register_gas",
    "merged_registry",
    "gas_to_dict",
    "describe_gas",
    "VACUUM_PERMITTIVITY_F_PER_M",
    "validate_geometry",
    "clamp_radius_to_geometry",
    "cylindrical_surface_field_v_per_m",
    "cylindrical_field_v_per_m",
    "potential_v",
    "track_radius_m",
    "radial_drift_distance_m",
    "mean_drift_path_radius_m",
    "average_drift_field_v_per_m",
    "wire_capacitance_per_length_f_per_m",
    "effective_wire_capacitance_f",
    "active_track_fraction",
    "direct_image_charge_sharing_factor",
    "geometry_summary",
    "geometry_from_mapping",
    "PRIMARY_ELECTRON_CHARGE_C",
    "EV_PER_MEV",
    "CM_PER_M",
    "IonizationEstimate",
    "track_energy_loss_mev",
    "track_energy_loss_ev",
    "mean_primary_electrons_from_energy_loss",
    "mean_primary_charge_c",
    "mean_cluster_count",
    "estimate_mean_ionization",
    "estimate_direct_image_charge_c",
    "ionization_summary",
    "estimate_primary_statistics_proxy",
    "DriftEstimate",
    "effective_drift_velocity_m_per_s",
    "estimate_drift_time_s",
    "estimate_attachment_survival_fraction",
    "estimate_collection_fraction_total",
    "estimate_collected_primary_electrons",
    "estimate_drift",
    "drift_summary",
    "GainEstimate",
    "estimate_gas_gain_from_surface_field",
    "estimate_gas_gain",
    "estimate_avalanche_electrons",
    "estimate_avalanche_charge_c",
    "estimate_gain",
    "gain_summary",
    "PulseComputation",
    "pulse_width_s",
    "rc_time_constant_s",
    "effective_pulse_width_s",
    "peak_current_a",
    "peak_voltage_v",
    "compute_pulse",
    "build_pulse_estimate",
    "build_direct_image_pulse",
    "build_avalanche_pulse",
    "pulse_summary",
    "build_estimator_config",
    "config_from_mapping",
    "estimate_from_config",
    "estimate",
    "estimate_to_dict",
    "result_to_dict",
    "estimate_from_mapping",
    "estimate_from_mapping_to_dict",
]